# Generated by Django 3.1.5 on 2021-02-04 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('ordinal', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('dateModified', models.DateTimeField(default=datetime.datetime.now)),
                ('activeFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
