# Generated by Django 3.1.5 on 2021-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='activeFlag',
            field=models.BooleanField(default=True),
        ),
    ]
