# Generated by Django 3.1.5 on 2021-02-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210204_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='ordinal',
        ),
    ]
