# Generated by Django 3.1.5 on 2021-02-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_highscore_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='userName',
            field=models.CharField(max_length=10),
        ),
    ]
