# Generated by Django 3.1.5 on 2021-02-06 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210205_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='dateModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
